# Generated by Django 2.1.5 on 2019-01-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='_id',
        ),
        migrations.AddField(
            model_name='event',
            name='unique_id',
            field=models.CharField(blank=True, max_length=232, null=True),
        ),
    ]
